### ISSUE TITLE
Question on how to run WinAppDriver

### ISSUE THREAD

**Issue by geovaneo** [Gene-R-Pool/BuggyFormTest#2]
Hi Gene! I am starting with WAP using Java, however I can only run my test if I open a CMD and run WAP first. Do you need to do the same or when you run the Java code it starts WAP in background?

I have WAp installed, developer mode enabled.

**Comment by Gene-R-Pool** [comment]
For the BuggyForm and BuggyFormTest I haven't put in any code to start WAD automatically. So I do manually start WAD from a batch file when I'm getting my environment ready to go.
On the page: https://plainswheeler.com/2019/08/26/common-winappdriver-errors/ under the Connection Refused heading I have some sample code posted that I've used in other projects to start WAD automatically. Best of luck working with WAD.
